<a href="https://colab.research.google.com/github/alwaysalearner1234/ML03/blob/main/Day5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Logic of KNN classification
# Choose the value of k (number of nearest neighbors)
# Plot all the data points in the coordinate system
# Calculate the distance from the data points to the predictive point
# Find the nearest points(k points) based on distance formula
# Check the labels/targets of the selected nearest points
# Based on majority of the labels, assign the label to the predictive point

In [1]:
#1.Let us take the data and create dataframe
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/ameenmanna8824/DATASETS/refs/heads/main/height_weight_knn.csv')
df

    Weight(x2)  Height(y2)        Class
0           51         167  Underweight
1           66         177       Normal
2           75         169   Overweight
3           69         176       Normal
4           50         173  Underweight
5           82         170   Overweight
6           65         172       Normal
7           58         180  Underweight
8           68         162   Overweight
9           63         165       Normal
10          52         174  Underweight
11          58         169       Normal
12          78         162   Overweight
13          65         168       Normal
14          62         183  Underweight
15          72         180       Normal
16          80         180   Overweight
17          60         178  Underweight
18          57         173       Normal
19          73         164   Overweight
20          53         170  Underweight
21          74         182       Normal
22          72         175   Overweight
23          53         163       Normal
24          55         180  Underweight

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Weight(x2)  25 non-null     int64
 1   Height(y2)  25 non-null     int64
 2   Class       25 non-null     object
dtypes: int64(2), object(1)
memory usage: 732.0+ bytes

In [3]:
#inputs:featres
df.isnull().sum()

Weight(x2)    0
Height(y2)    0
Class         0
dtype: int64

In [ ]:
# Inputs : Features
# Outputs: Labels/Targets

In [5]:
X = df[['Weight(x2)','Height(y2)']].values
y = df['Class'].values

In [ ]:
# splitting of data into training and testing datasets
# from sklearn.model_selection import train_test_split

In [6]:
from sklearn.neighbors import KNeighborsClassifier

In [7]:
model = KNeighborsClassifier(n_neighbors=5,metric='euclidean')

In [8]:
model.fit(X,y)

KNeighborsClassifier(metric='euclidean')

In [9]:
model.predict([[54.2,167.5]])

array(['Normal'], dtype=object)

In [10]:
import joblib
joblib.dump(model,'knn_model')

['knn_model']

In [11]:
!pip install streamlit --quiet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 48.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.4/11.4 MB 60.1 MB/s eta 0:00:00

In [12]:
%%writefile app.py
import streamlit as st
import joblib
model = joblib.load('knn_model')
st.header("BMI predictor Applet")
w = st.number_input("Enter the weight(in kg)",min_value=40,max_value=90,step=1)
h = st.number_input("Enter the height(in cm)",min_value=135,max_value=200,step=1)
if st.button("PREDICT CLASS"):
    op = model.predict([[w,h]])
    st.subheader(f"The person with above weight and height is classified as {op[0]}.")

Writing app.py

In [13]:
!streamlit run app.py & npx localtunnel --port 8501

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙Need to install the following packages:
localtunnel@2.0.2
Ok to proceed? (y)
Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

2026-07-31 06:09:27.496 Uvicorn server started on :::8501

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://34.11.87.232:8501

y

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧your url is: https://famous-cats-stand.loca.lt
  Stopping...
^C